export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_LOCATION_STATE_CHANGE = 'USER_LOCATION_STATE_CHANGE'
export const USER_FRIENDS_STATE_CHANGE = 'USER_FRIENDS_STATE_CHANGE'
export const USER_FRIEND_REQUESTS_STATE_CHANGE = 'USER_FRIEND_REQUESTS_STATE_CHANGE'
export const USER_FRIEND_REQUESTS_SENT_STATE_CHANGE = 'USER_FRIEND_REQUESTS_SENT_STATE_CHANGE'
export const USER_FRIENDS_DATA_STATE_CHANGE = 'USER_FRIENDS_DATA_STATE_CHANGE'
export const USER_BARS_STATE_CHANGE = 'USER_BARS_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LAST_POST_STATE_CHANGE = 'USERS_LAST_POST_STATE_CHANGE'
export const USERS_ALL_POSTS_STATE_CHANGE = 'USERS_ALL_POSTS_STATE_CHANGE'


export const CLEAR_DATA = 'CLEAR_DATA'